'use client';
import {useEffect,useMemo,useState,useRef} from 'react';
import {flushSync} from 'react-dom';
import {ArrowDownRight,ArrowUpRight,ArrowRight,RotateCcw,Play,Pause,Download,ExternalLink,Landmark,SlidersHorizontal,Info,ChevronDown,Moon,Sun} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Slider} from '@/components/ui/slider';
import {defaults,presets,simulate,type Config,type Point} from '@/lib/simulator';
import {createTranslator,createFormatters,readPreferences,type Language,type Theme} from '@/lib/i18n';
import {usePointerLight} from '@/hooks/use-pointer-light';
import {pointerDay,keyboardDay} from '@/lib/chart-interaction';
function Control({label,value,min,max,step=1,onChange,format=String,hint}:{label:string;value:number;min:number;max:number;step?:number;onChange:(v:number)=>void;format?:(v:number)=>string;hint?:string}){
 return <div className="control"><div className="control-label"><label>{label}</label><output>{format(value)}</output></div><Slider aria-label={label} value={[value]} min={min} max={max} step={step} onValueChange={v=>onChange(Array.isArray(v)?v[0]:v)}/>{hint&&<p>{hint}</p>}</div>;
}
function Chart({points,baseline,day,mode,language,onSelectDay}:{points:Point[];baseline:Point[];day:number;mode:'held'|'fee'|'branches';language:Language;onSelectDay:(day:number)=>void}){
 const t=createTranslator(language),{compact,num,pct}=createFormatters(language);
 const chartRef=useRef<SVGSVGElement>(null),[w,setChartWidth]=useState(760);
 const [hoverDay,setHoverDay]=useState<number|null>(null);
 useEffect(()=>{
  if(!chartRef.current||typeof ResizeObserver==='undefined')return;
  const observer=new ResizeObserver(entries=>{const width=entries[0]?.contentRect.width;if(width)setChartWidth(Math.max(260,width));});
  observer.observe(chartRef.current);
  return()=>observer.disconnect();
 },[]);
 const h=240,l=65,r=15,top=16,b=30;
 const max=mode==='fee'?Math.max(.1,...points.map(p=>p.fee))*1.15:Math.max(...points.map(p=>p[mode]),...(mode==='held'?baseline.map(p=>p.held):[]))*1.12;
 const x=(d:number)=>l+d/14*(w-l-r),y=(v:number)=>h-b-v/max*(h-top-b);
 const path=(data:Point[])=>data.map((p,i)=>`${i?'L':'M'}${x(p.day)},${y(p[mode])}`).join(' ');
 const actual=points.slice(0,day+1),last=points[day];
 const inspected=points[hoverDay??day];
 const inspectValue=mode==='fee'?pct(inspected.fee):num(inspected[mode]);
 function dayFromPointer(clientX:number){const rect=chartRef.current?.getBoundingClientRect();return rect?pointerDay(clientX,rect.left,rect.width,w):day;}
 return <div className="chart-interactive"><div className="chart-inspector"><span className="inspector-day">{t(hoverDay===null?'Selected':'Preview')} · {t('Day')} {inspected.day}</span><strong>{inspectValue}<small>{mode==='held'?' STANDARD':mode==='branches'?` ${t('Branches')}`:''}</small></strong></div><p className="chart-instruction">{t('Hover to inspect. Click or use arrow keys to select a day.')}</p><svg ref={chartRef} className="chart" viewBox={`0 0 ${w} ${h}`} role="slider" tabIndex={0} aria-label={t('Simulation day')} aria-valuemin={0} aria-valuemax={14} aria-valuenow={day} aria-valuetext={t('{metric} over 14 simulated days. Day {day}: {value}. Exact results in daily ledger.',{metric:t(mode==='held'?'Branch balance':mode==='fee'?'Exit fee':'Branches'),day,value:mode==='fee'?pct(last.fee):num(last[mode])})}
 onPointerMove={event=>{if(event.pointerType==='mouse')setHoverDay(dayFromPointer(event.clientX));}} onPointerLeave={()=>setHoverDay(null)} onBlur={()=>setHoverDay(null)} onClick={event=>{onSelectDay(dayFromPointer(event.clientX));setHoverDay(null);}} onKeyDown={event=>{const next=keyboardDay(event.key,day);if(next!==null){event.preventDefault();setHoverDay(null);onSelectDay(next);}}}>
 <defs><linearGradient id="area" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="var(--chart-green)" stopOpacity=".17"/><stop offset="100%" stopColor="var(--chart-green)" stopOpacity="0"/></linearGradient></defs>
 {[0,.25,.5,.75,1].map(v=><g key={v}><line x1={l} x2={w-r} y1={y(max*v)} y2={y(max*v)} stroke="var(--chart-grid)" strokeDasharray="3 5"/><text x={l-10} y={y(max*v)+4} textAnchor="end">{mode==='fee'?pct(max*v):compact(max*v)}</text></g>)}
 {(w<450?[0,4,8,14]:[0,2,4,6,8,10,12,14]).map(d=><text key={d} x={x(d)} y={h-5} textAnchor="middle">{t("D")}{d}</text>)}
 {mode==='held'&&<path d={path(baseline)} fill="none" stroke="var(--chart-baseline)" strokeWidth="2" strokeDasharray="5 6"/>}
 <path d={path(points)} fill="none" stroke="var(--chart-future)" strokeWidth="2"/><path className="chart-area" d={`${path(actual)} L${x(day)},${h-b} L${l},${h-b} Z`} fill="url(#area)"/><path className="chart-line" key={`${mode}-${day}-${last[mode]}`} pathLength="1" d={path(actual)} fill="none" stroke="var(--chart-green)" strokeWidth="3" strokeLinecap="round" strokeLinejoin="round"/><line x1={x(day)} x2={x(day)} y1={top} y2={h-b} stroke="var(--chart-guide)" strokeDasharray="3 4"/><circle className="chart-current-dot" cx={x(day)} cy={y(last[mode])} r="5" fill="var(--chart-green)" stroke="var(--surface)" strokeWidth="3"/>
 {hoverDay!==null&&<g className="chart-crosshair" pointerEvents="none"><line x1={x(hoverDay)} x2={x(hoverDay)} y1={top} y2={h-b} stroke="var(--chart-green)" strokeOpacity=".55" strokeDasharray="2 4"/><circle cx={x(hoverDay)} cy={y(inspected[mode])} r="11" fill="var(--chart-green)" fillOpacity=".12"/><circle cx={x(hoverDay)} cy={y(inspected[mode])} r="4" fill="var(--surface)" stroke="var(--chart-green)" strokeWidth="2"/></g>}
 </svg></div>;
}
export default function Home(){
 const siteRef=useRef<HTMLDivElement>(null);
 usePointerLight(siteRef);
 const [language,setLanguage]=useState<Language>('en'),[theme,setTheme]=useState<Theme>('light'),[preferencesReady,setPreferencesReady]=useState(false);
 const t=createTranslator(language),{compact,num,pct,decimal}=createFormatters(language);
 useEffect(()=>{
   try { const saved=readPreferences(window.localStorage,window.matchMedia('(prefers-color-scheme: dark)').matches);setLanguage(saved.language);setTheme(saved.theme); } catch {}
   setPreferencesReady(true);
 },[]);
 useEffect(()=>{
   if(!preferencesReady)return;
   document.documentElement.dataset.theme=theme;
   document.documentElement.lang=language;
   document.title=createTranslator(language)('Bank Run Simulator — Standard Reserve Community Lab');
   try { localStorage.setItem('sr-language',language);localStorage.setItem('sr-theme',theme); } catch {}
 },[theme,language,preferencesReady]);
 const [config,setConfig]=useState<Config>(defaults),[preset,setPreset]=useState('run'),[day,setDay]=useState(7),[playing,setPlaying]=useState(false),[mode,setMode]=useState<'held'|'fee'|'branches'>('held');
 const points=useMemo(()=>simulate(config),[config]),baseline=useMemo(()=>simulate({...config,exits:0}),[config]);
 const p=points[day],b=baseline[day];
 function change(key:keyof Config,value:Config[keyof Config]){setConfig(c=>({...c,[key]:value}));setPreset('custom');setPlaying(false);}
 function choose(id:string){setConfig(c=>({...c,...presets[id].config}));setPreset(id);setDay(7);setPlaying(false);}
 useEffect(()=>{if(!playing)return;const timer=setInterval(()=>setDay(d=>Math.min(14,d+1)),650);return()=>clearInterval(timer);},[playing]);
 useEffect(()=>{if(day===14)setPlaying(false);},[day]);
 useEffect(()=>{
  type Tool={name:string;description:string;inputSchema:object;annotations:object;execute:(input:unknown)=>unknown};
  const ctx=(document as Document&{modelContext?:{registerTool:(tool:Tool,opts:{signal:AbortSignal})=>void|Promise<void>}}).modelContext;if(!ctx)return;
  const lifecycle=new AbortController();
  const tool:Tool={name:'set_simulation_scenario',description:'Select a visible educational scenario and day. No financial actions.',inputSchema:{type:'object',properties:{scenario:{type:'string',enum:Object.keys(presets)},day:{type:'integer',minimum:0,maximum:14}},required:['scenario','day'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input){const v=input as {scenario:string;day:number};if(!v||!Object.hasOwn(presets,v.scenario)||!Number.isInteger(v.day)||v.day<0||v.day>14)throw new Error('Invalid scenario or day');const next={...defaults,...presets[v.scenario].config};flushSync(()=>{setConfig(next);setPreset(v.scenario);setDay(v.day);setPlaying(false);});return {assumptions:true,...simulate(next)[v.day]};}};
  try{Promise.resolve(ctx.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{});}catch{}return()=>lifecycle.abort();
 },[]);
 function download(){const rows=points.map(v=>[v.day,v.branches,v.ledger,v.held,v.paid,v.burned,v.recycled,v.fee*100,v.pressure*100,v.multiplier,v.issued].join(','));const blob=new Blob([`# ${t('Educational assumptions; not live data')}\n# config=${JSON.stringify(config)}\n${language==='ru'?'день,отделения,баланс_STANDARD,на_отделение_STANDARD,выплачено_STANDARD,сожжено_эквивалент_STANDARD,перераспределено_STANDARD,комиссия_процент,давление_процент,множитель,эмиссия_STANDARD':'day,active_branches,ledger_STANDARD,per_branch_STANDARD,paid_STANDARD,fee_burn_equivalent_STANDARD,redistributed_STANDARD,fee_pct,pressure_pct,multiplier,issued_STANDARD'}\n${rows.join('\n')}`],{type:'text/csv'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='standard-bank-run-simulation.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 return <div ref={siteRef} className="site" data-playing={playing}><header className="topbar"><a className="brand" href="#"><span className="brand-icon"><Landmark size={19}/></span><span>STANDARD RESERVE <span className="lab">{t("/ COMMUNITY LAB")}</span></span></a><div className="header-actions"><div className="language-switch" role="group" aria-label={t("Language")}><Button variant="ghost" aria-pressed={language==='en'} onClick={()=>setLanguage('en')} lang="en">EN</Button><Button variant="ghost" aria-pressed={language==='ru'} onClick={()=>setLanguage('ru')} lang="ru">RU</Button></div><Button className="theme-switch" variant="outline" size="icon" aria-label={t(theme==='light'?'Switch to dark theme':'Switch to light theme')} title={t(theme==='light'?'Switch to dark theme':'Switch to light theme')} onClick={()=>setTheme(v=>v==='light'?'dark':'light')}>{theme==='light'?<Moon size={18}/>:<Sun size={18}/>}</Button><a className="source-link" href="https://www.standardreserve.xyz/whitepaper/" target="_blank" rel="noreferrer">{t("Read the whitepaper")}{" "}<ArrowUpRight size={15}/></a></div></header>
 <main><div className="page-heading"><div><div className="eyebrow"><span className="live-dot"/> {t("INTERACTIVE MECHANICS EXPLORER")}</div><h1>{t("What happens when")}<br className="mobile-break"/> {t("everyone wants out")}<span>?</span></h1><p>{t("Retire branches. Follow the fees. See what changes for the bankers who stay.")}</p></div><div className="heading-stamp">{t("Bank Run")}<br/><strong>{t("Simulator")}</strong><span>{t("01 — INDEPENDENT STUDY")}</span></div></div>
 <div className="notice"><Info size={16}/><p><strong>{t("A model, not a prediction.")}</strong> {t("Core mechanics follow the whitepaper. Hidden launch parameters are adjustable assumptions. No live data, price forecast or wallet connection.")}</p><a href="#methodology">{t("Model notes")}{" "}<ArrowDownRight size={14}/></a></div>
 <div className="workspace"><aside className="panel controls-panel"><div className="section-title"><h2>{t("Set the conditions")}</h2><SlidersHorizontal size={17}/></div><p className="muted">{t("Pick a scenario, then make it your own.")}</p><div className="presets">{Object.entries(presets).map(([key,v])=><button key={key} aria-pressed={preset===key} onClick={()=>choose(key)} className={`preset ${preset===key?'selected':''}`}><span className={`scenario-dot ${key}`}/><span><strong>{t(v.label)}</strong><small>{t(v.note)}</small></span><span className="radio-mark"/></button>)}</div><div className="divider"/>
 <Control label={t("Branches retiring in 7 days")} value={config.exits} min={0} max={95} format={v=>v+'%'} onChange={v=>change('exits',v)} hint={t('{count} of 1,000 starting branches close. Not a % of token sellers.',{count:num(config.exits*10)})}/>
 <Control label={t("Net pool flow / day")} value={config.flow} min={-100} max={100} format={v=>`${v>0?'+':''}${v} ETH`} onChange={v=>change('flow',v)} hint={t("Separate trading assumption. Only the sign affects policy. Branch exits do not automatically sell tokens.")}/>
 <div className="control-label"><span>{t("Exit timing")}</span></div><div className="segmented pace">{(['steady','front'] as const).map(v=><button key={v} aria-pressed={config.pace===v} className={config.pace===v?'active':''} onClick={()=>change('pace',v)}>{v==='steady'?t("Evenly spread"):t("Rush at the start")}</button>)}</div>
 <details className="assumptions"><summary>{t("Assumed parameters")}{" "}<ChevronDown size={15}/></summary><div className="assumption-content"><p>{t("Illustrative values, not announced launch settings.")}</p><Control label={t("Base issuance / day")} value={config.base} min={0} max={500000} step={10000} format={compact} onChange={v=>change('base',v)}/><Control label={t("Starting ledger balance")} value={config.balance} min={1000000} max={50000000} step={1000000} format={compact} onChange={v=>change('balance',v)}/><Control label={t("Minimum exit fee")} value={config.floor} min={0} max={20} format={v=>v+'%'} onChange={v=>change('floor',v)}/><Control label={t("Maximum exit fee")} value={config.ceiling} min={20} max={70} format={v=>v+'%'} onChange={v=>change('ceiling',v)}/><Control label={t("Pressure at maximum fee")} value={config.saturation} min={10} max={100} format={v=>v+'%'} onChange={v=>change('saturation',v)}/></div></details>
 <Button className="reset" variant="ghost" onClick={()=>{setConfig(defaults);setPreset('run');setDay(7);setPlaying(false);}}><RotateCcw size={14}/> {t("Reset experiment")}</Button></aside>
 <section className="results"><div className="result-top"><span className="eyebrow">{t("THE SYSTEM AT DAY")}{" "}{String(day).padStart(2,'0')}</span><span className={`regime ${config.flow>0?'expansion':''}`}>{config.flow>0?<ArrowUpRight size={13}/>:<ArrowDownRight size={13}/>} {config.flow>0?t("Expansion"):t("Contraction")} {t("scenario")}</span></div>
 <div className="metrics"><div className="metric"><span>{t("Active branches")}</span><strong><span className="value-arrive" key={num(p.branches)}>{num(p.branches)}</span><small>{t("/ 1,000")}</small></strong><p>{num(1000-p.branches)} {t("retired permanently")}</p></div><div className="metric"><span>{t("Modeled exit fee")}</span><strong><span className="value-arrive" key={pct(p.fee)}>{pct(p.fee)}</span></strong><p>{pct(p.pressure)} {t("rolling exit pressure")}</p></div><div className="metric"><span>{t("Daily issuance rate")}</span><strong><span className="value-arrive" key={compact(config.base*p.multiplier)}>{compact(config.base*p.multiplier)}</span><small>STD</small></strong><p>{decimal(p.multiplier)}{t("× assumed base rate")}</p></div></div>
 <div className="panel chart-panel"><div className="chart-heading"><div><h2>{mode==='held'?t("The view from a surviving branch"):mode==='fee'?t("The cost of leaving"):t("Fewer branches. A different share.")}</h2><p>{mode==='held'?t("Accrued balance per branch · $STANDARD, not cash"):mode==='fee'?t("Quadratic fee on each modeled daily withdrawal cohort"):t("Active earning branches · no new openings in this model")}</p></div><span className="day-pill">{t("DAY")}{" "}{day}</span></div>
 <div className="segmented chart-tabs">{([['held',t("Branch balance")],['fee',t("Exit fee")],['branches',t("Branches")]] as const).map(([key,label])=><button key={key} className={mode===key?'active':''} aria-pressed={mode===key} onClick={()=>setMode(key)}>{label}</button>)}</div><Chart points={points} baseline={baseline} day={day} mode={mode} language={language} onSelectDay={value=>{setPlaying(false);setDay(value);}}/><div className="chart-legend"><span><i/>{t("Selected scenario")}</span>{mode==='held'&&<span><i className="baseline"/>{t("No exits · same pool flow")}</span>}<span className="forecast-label">{t("Pale line: remaining simulated days")}</span></div>
 <div className="timeline"><Button aria-label={playing?t("Pause simulation"):t("Play simulation")} className="play" size="icon" onClick={()=>{if(day>=14)setDay(0);setPlaying(v=>!v);}}>{playing?<Pause size={15}/>:<Play size={15}/>}</Button><span>{t("Day")}{" "}{day}</span><Slider aria-label={t("Simulation day")} value={[day]} min={0} max={14} step={1} onValueChange={v=>{setPlaying(false);setDay(Array.isArray(v)?v[0]:v);}}/><span>14</span><Button variant="ghost" size="icon" aria-label={t("Advance one day")} disabled={day===14} onClick={()=>{setPlaying(false);setDay(d=>Math.min(14,d+1));}}><ArrowRight size={17}/></Button></div></div>
 <div className="insight"><div className="insight-symbol">↗</div><div><h3>{day===0?t("Start with equal balances. Let behavior change the outcome."):t('{amount} STANDARD accrued per surviving branch.',{amount:compact(p.held)})}</h3><p>{day===0?t("Move through time to see the exits, fee split and issuance adjustment."):t('{amount} more than the no-exit baseline at the same pool flow. Fewer branches split new issuance, and half the exit fees return to the remaining ledger.',{amount:compact(p.held-b.held)})} <strong>{t("This is not a cash return: exiting still incurs a fee, and token price can fall.")}</strong></p></div></div></section></div>
 <section className="distribution"><div className="section-title"><div><span className="eyebrow">{t("FOLLOW THE WITHDRAWAL")}</span><h2>{t("Where does the balance go?")}</h2></div><span className="muted">{t("Cumulative through day")}{" "}{day} {t("· STANDARD units")}</span></div><div className="flow-cards">{[
 ['01',t("Released by retiring branches"),p.paid+p.burned+p.recycled,t("Gross accrued balance leaving its original branches."),''],
 [t("02 / TO EXITERS"),t("Tokens paid to wallets"),p.paid,t("After the fee. Not equivalent to ETH received."),'paid'],
 [t("03 / HALF THE FEE"),t("Removed permanently"),p.burned,t("Burned fee entitlement, in token-equivalent units."),''],
 [t("04 / HALF THE FEE"),t("Redistributed to stayers"),p.recycled,t("Accrued to surviving positions, not immediately cashed out."),'recycled']
 ].map(([id,label,value,note,cls])=><div key={id} className={`flow-card ${cls}`}><span className="flow-number">{id}</span><span>{label}</span><strong><span className="value-arrive" key={compact(Number(value))}>{compact(Number(value))}</span></strong><p>{note}</p></div>)}</div></section>
 <section className="bottom-grid"><div className="panel policy-panel"><span className="eyebrow">{t("THE OTHER DEFENSE")}</span><h2>{t("Exits and selling are not the same.")}</h2><p>{t("Retiring a branch releases tokens. Selling those tokens into the pool is a separate action. The pool’s ETH flow drives monetary policy.")}</p><div className="policy-row"><span>{t("Pool flow assumption")}</span><strong>{config.flow>0?'+':''}{config.flow} {t("ETH / day")}</strong></div><div className="policy-row"><span>{t("70% of protocol ETH fees")}</span><strong>{config.flow>0?t("Reserve accumulation"):t("Buyback vault")}</strong></div><div className="policy-row"><span>{t("Remaining fee allocation")}</span><strong>{t("15% liquidity · 15% team")}</strong></div><p className="footnote">{t("Routing only — no trading fee revenue, pool execution or token-price model is invented here. Buybacks do not guarantee price support.")}</p></div>
 <div className="panel bank-panel"><span className="eyebrow">{t("THE LEDGER IS NOT THE MARKET")}</span><h2>{t("Keep the units honest.")}</h2><div className="ledger-stat"><span>{t("Still accrued in the bank")}</span><strong><span className="value-arrive" key={compact(p.ledger)}>{compact(p.ledger)}</span> <small>STANDARD</small></strong></div><div className="ledger-stat"><span>{t("Daily rate per surviving branch¹")}</span><strong><span className="value-arrive" key={num(p.dailyYield)}>{num(p.dailyYield)}</span> <small>{t("STANDARD / day")}</small></strong></div><p>{t("Balances are accounting entries until withdrawal. A larger token balance is not proof of a larger dollar value.")}</p><p className="footnote">{t("¹ At the current multiplier, before the next policy update.")}</p></div></section>
 <section id="methodology" className="methodology"><div className="section-title"><div><span className="eyebrow">{t("OPEN THE BLACK BOX")}</span><h2>{t("Rules, assumptions & limits.")}</h2></div><a href="https://www.standardreserve.xyz/whitepaper/" target="_blank" rel="noreferrer">{t("Whitepaper v0.1")}{" "}<ExternalLink size={14}/></a></div><div className="method-grid"><div><h3><span className="tag confirmed">{t("Documented mechanics")}</span></h3><ul><li>{t("Branch retirement releases its proportional accrued balance and removes its future issuance share.")}</li><li>{t("A quadratic resolution fee rises with trailing 7-day withdrawal pressure. Half is burned; half goes to remaining bankers.")}</li><li>{t("Issuance is shared across branches. Policy reads two completed epochs; fee routing reads current flow.")}</li><li>{t("1B supply cap: 100M genesis tokens and a 900M cumulative issuance budget.")}</li></ul></div>
 <div><h3><span className="tag assumed">{t("Explicit model assumptions")}</span></h3><ul><li>{t("1,000 equally funded branches; one-day epochs; no new branches, auctions, dormancy or charter transfers. At least 50 branches stay.")}</li><li>{t("Daily batches accrue issuance, retire branches, then redistribute fees equally per surviving branch. Actual transaction order can differ.")}</li><li>{t("Fee = floor + (ceiling − floor) × min(pressure / saturation, 1)². Pressure includes today’s batch: W / max(D + W, 1), before fee redistribution. W is gross withdrawals in the current and previous six days; D is the remaining ledger.")}</li><li>{t("Multiplier starts at 1×, rises by 0.05 for a positive two-epoch signal, falls by 0.15 for a negative signal, stays flat at zero; bounded at 0.20–1.25×. Pre-simulation flows are zero. All these policy values are assumptions.")}</li></ul></div>
 <div><h3><span className="tag excluded">{t("Not a contract replica")}</span></h3><ul><li>{t("Official launch values are redacted. The whitepaper is a design overview, not an implementation specification.")}</li><li>{t("No token price, slippage, ETH redemption, live reserves or solvency calculation. Staying is not a guaranteed winning strategy.")}</li><li>{t("Fee burning is tracked as cancelled token entitlement, not asserted as an onchain mint/burn event.")}</li><li>{t("The initial ledger counts toward the 900M budget. Only new base issuance consumes further budget; recycled fees do not.")}</li><li>{t("Rush timing: 40%, 20%, 13%, 10%, 7%, 6%, 4% of the planned exits across seven days. Branch counts are rounded.")}</li></ul></div></div><p className="source-note">{t("Source checked 8 September 2026:")}{" "}<a href="https://www.standardreserve.xyz/whitepaper/#exits">{t("§9 Withdrawals")}</a> · <a href="https://www.standardreserve.xyz/whitepaper/#policy">{t("§5 Monetary policy")}</a> · <a href="https://www.standardreserve.xyz/whitepaper/#reserves">{t("§11 Fee routing")}</a>{t(". Independently built; not affiliated with or endorsed by Standard Reserve or 0xbeans.")}</p></section>
 <details className="daily-ledger"><summary><span>{t("Daily ledger")}{" "}<small>{t("Inspect the numbers behind the chart")}</small></span><ChevronDown size={18}/></summary><div className="table-actions"><Button variant="outline" onClick={download}><Download size={14}/> {t("Export CSV")}</Button></div><div className="table-scroll"><table><caption>{t("All values are simulated. Balances and payouts are in STANDARD.")}</caption><thead><tr>{[t("Day"),t("Branches"),t("Exit fee"),t("Multiplier"),t("Per branch"),t("Paid to wallets"),t("Fee burned"),t("Redistributed")].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{points.map(v=><tr key={v.day} className={v.day===day?'current-row':''}><td><button onClick={()=>{setDay(v.day);setPlaying(false);}}>{t("D")}{v.day}</button></td><td>{num(v.branches)}</td><td>{pct(v.fee)}</td><td>{decimal(v.multiplier)}×</td><td>{num(v.held)}</td><td>{num(v.paid)}</td><td>{num(v.burned)}</td><td>{num(v.recycled)}</td></tr>)}</tbody></table></div></details>
 </main><footer><div className="footer-brand"><Landmark size={16}/> {t("BANK RUN SIMULATOR")}{" "}<span>{t("Learn the mechanics. Question the assumptions.")}</span></div><a href="https://x.com/intelpocik" target="_blank" rel="noreferrer">by @intelpocik <ArrowUpRight size={14}/></a></footer></div>;
}
